server:
  host: localhost
  port: 8000  
database:
  host: localhost
  username: postgres
  dbname: db_time_tracker
  port: 5432
  sslmode: disable


# migrate -source file://schema -database "postgresql://postgres:qwer123@localhost:5432/db_time_tracker?sslmode=disable" -verbose up